SELECT T0."CardCode"
	,T0."CardName"
	,T0."AliasName"
	,T0."E_Mail"
	,T0."SlpCode"
	,T0."HousBnkAct"
	,T0."GroupNum"
	,T0."GroupCode"
	,T0."ProjectCod"
	,T0."ShipType"
    ,T0."SlpCode"
	,T2."AddrType"
	,T2."Street"
	,T2."StreetNo" 
	,T2."Block"
	,T2."State"
	,T2."City"
	,T2."Country"
	,T2."Building"
	,T0."U_TaktTime"
	,T0."U_TransitTime"
    ,T0."CardCode" || ' - ' || T0."CardName" As "Fornecedor"

FROM "SUA_TABELA"."OCRD" T0
INNER JOIN "SUA_TABELA"."CRD1" T2 ON T0."CardCode" = T2."CardCode"
AND T2."Address" = T0."ShipToDef"
WHERE T0."GroupCode" = '106' OR  T0."GroupCode" = '121'
